# Sidebar navigation

- label: Introduction
  link: "/"
- label: Getting Started
  link: "/getting-started"
- label: Functional Modules
  link: "/functional-modules"
- label: Create your own module
  link: "/create-your-own"
- label: Authentication & Authorization
  link: "/roles"
- label: Built-in Functional Modules
  items:
    - label: Devtools
      link: "fm/devtools"
    - label: Data Browser
      link: "fm/data-browser"
    - label: Chat Module
      link: "fm/chat-module"
    - label: Files Manager
      link: "fm/files-manager"
