# Sidebar navigation

- label: Introduction
  link: "/"
- label: Getting Started
  link: "/getting-started"
- label: Functional Modules
  items:
    - label: Introduction
      link: "fm-tutorial/introduction"
    - label: Initial Setup
      link: "fm-tutorial/initial-setup"
    - label: Bootstraps
      link: "fm-tutorial/bootstraps"
    - label: IAM
      link: "fm-tutorial/iam"
    - label: Controllers
      link: "fm-tutorial/controllers"
    - label: Models
      link: "fm-tutorial/models"
    - label: Authentication & Authorization
      link: "fm-tutorial/roles"
- label: Built-in Functional Modules
  items:
    - label: Devtools
      link: "fm/devtools"
    - label: Data Browser
      link: "fm/data-browser"
    - label: Chat Module
      link: "fm/chat-module"
    - label: Files Manager
      link: "fm/files-manager"
