# Sidebar navigation

- label: Introduction
  link: "/"
- label: Getting Started
  link: "/getting-started"
- label: Functional Modules
  items:
    - label: Introduction
      link: "fm/introduction"
    - label: Built-in Functional Modules
      link: "fm/functional-modules"
    - label: "Creating Your Own Functional Module"
      link: "fm/creating"
    - label: "Authentication & Authorization"
      link: "fm/auth"
